image: ubuntu_gradle_jdk:latest

stages:
  - build

full_build:
  stage: build
  only:
    - master
    - develop
  script:
#    - apt-get update
#    - apt-get install --yes --force-yes gradle
    - rm -rf build/libs/*
    - sudo ./gradlew.bat setupCIWorkspace
    - sudo ./gradlew.bat build
    - sudo ./gradlew.bat artifactoryPublish
  cache:
    untracked: true
    key: "$CI_BUILD_NAME"