image: java:8-jdk

stages:
  - setup
  - build
  - test
  - publish

cache:
  untracked: true
  key: "default"
  paths:
    - .gradle/
    - src/
    - build/  

setup_forge:
  stage: setup
  only:
   - master
   - develop
  script:
    - rm -rf build/libs/*
    - chmod +x ./gradlew
    - ./gradlew setupCIWorkspace

build_mod:
  stage: build
  only:
    - master
    - develop
  script:
    - ./gradlew build -x test

test_mod:
  stage: test
  only:
    - master
    - develop
  script:
    - ./gradlew test
  cache:
    policy: pull

publish_mod:
  stage: publish
  only:
    - master
    - develop
  script:
    - ./gradlew artifactoryPublish
  cache:
    policy: pull